/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActivityItemsSource.h"
#import <Foundation/NSObject.h>

@class NSURL, BrowserPrintPageRenderer, UIPrintInfo;

__attribute__((visibility("hidden")))
@interface ActionPanelActivityItemsSource : NSObject <UIActivityItemsSource> {
	BrowserPrintPageRenderer* _printRenderer;
	UIPrintInfo* _printInfo;
	NSURL* _urlToShare;
}
-(id)activityViewController:(id)controller itemsForActivityType:(id)activityType;
-(id)activityViewControllerPlaceholderItems:(id)items;
-(id)_activityItemsIncludingURLAsString:(BOOL)string;
-(id)_customActivities;
-(void)dealloc;
@end

