/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BrowserPanel.h"
#import <UIKit/UIActivityViewController.h>


__attribute__((visibility("hidden")))
@interface ActionPanel : UIActivityViewController <BrowserPanel> {
	BOOL _inCancel;
	BOOL _inCompletionHandler;
}
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)_shouldSendBrowserPanelNotification;
-(void)willHideOnSuspend;
-(BOOL)shouldResumePanel;
-(void)panelWillSuspend;
-(BOOL)shouldHideOnSuspend;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)pausesPages;
-(int)panelState;
-(int)panelType;
-(void)_preparePrint:(id)print;
-(void)_prepareMail:(id)mail;
-(void)_preparePostToSocialNetwork:(id)socialNetwork;
-(void)_prepareActivity:(id)activity;
-(void)_executeActivity;
-(void)_cancel;
-(void)cancelActionPanel;
-(void)_activityDidComplete:(id)_activity withSuccess:(BOOL)success;
-(id)init;
@end

