/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UINavigationController.h>
#import "BookmarkInfoViewControllerDelegate.h"

@class WebBookmarkCollection, BookmarkInfoViewController, NSObject;
@protocol AddBookmarkNavigationControllerDelegate;

__attribute__((visibility("hidden")))
@interface AddBookmarkNavigationController : UINavigationController <BookmarkInfoViewControllerDelegate> {
	BookmarkInfoViewController* _infoViewController;
	WebBookmarkCollection* _collection;
	NSObject<AddBookmarkNavigationControllerDelegate>* _bookmarkNavDelegate;
	BOOL _delegateNotifiedOfResult;
}
@property(assign, nonatomic) NSObject<AddBookmarkNavigationControllerDelegate>* bookmarkNavDelegate;
-(void)bookmarkInfoViewController:(id)controller didFinishWithResult:(BOOL)result;
-(void)viewDidDisappear:(BOOL)view;
-(void)_popFromKeyboardReturn;
-(void)willHideOnSuspend;
-(BOOL)shouldResumePanel;
-(void)panelWillSuspend;
-(BOOL)shouldShowBrowserPanel;
-(void)addBookmarkWithTitle:(id)title address:(id)address;
-(void)dealloc;
-(id)initWithCollection:(id)collection;
@end

