/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIActivity.h>


__attribute__((visibility("hidden")))
@interface AddToReadingListUIActivity : UIActivity {
}
-(void)performActivity;
-(BOOL)canPerformWithActivityItems:(id)activityItems;
-(id)activityImage;
-(id)activityTitle;
-(id)activityType;
@end

