/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSURLProtocol.h>


__attribute__((visibility("hidden")))
@interface AppBundleURLProtocol : NSURLProtocol {
}
+(BOOL)requestIsCacheEquivalent:(id)equivalent toRequest:(id)request;
+(id)canonicalRequestForRequest:(id)request;
+(BOOL)canInitWithRequest:(id)request;
+(id)URLForResourceAtPath:(id)path;
+(id)URLScheme;
+(void)registerProtocol;
+(void)initialize;
-(void)stopLoading;
-(void)startLoading;
-(void)_sendDataToClient:(id)client forURL:(id)url;
-(void)_sendURLErrorToClient:(int)client forURL:(id)url;
-(void)_sendURLErrorToClient:(int)client withUserInfo:(id)userInfo;
@end

