/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UINavigationController.h>
#import "BackForwardTableViewControllerDelegate.h"
#import "BrowserPanel.h"

@class BackForwardTableViewController, NSArray;

__attribute__((visibility("hidden")))
@interface BackForwardNavigationController : UINavigationController <BrowserPanel, BackForwardTableViewControllerDelegate> {
	BackForwardTableViewController* _tableViewController;
}
@property(assign, nonatomic) BOOL reversesListOrder;
@property(copy, nonatomic) NSArray* backForwardList;
-(BOOL)shouldShowButtonBar;
-(id)toolbarItems;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)pausesPages;
-(int)panelState;
-(int)panelType;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(id)rotatingFooterView;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)backForwardTableViewController:(id)controller didSelectWebHistoryItem:(id)item;
-(void)done;
-(void)dealloc;
-(id)init;
@end

