/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PopoverSizingTableViewController.h"

@class NSArray;
@protocol BackForwardTableViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface BackForwardTableViewController : PopoverSizingTableViewController {
	id<BackForwardTableViewControllerDelegate> _delegate;
	NSArray* _backForwardList;
	BOOL _reversesListOrder;
}
@property(assign, nonatomic) BOOL reversesListOrder;
@property(copy, nonatomic) NSArray* backForwardList;
@property(assign, nonatomic) id<BackForwardTableViewControllerDelegate> delegate;
-(void)dealloc;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)indexForIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
@end

