/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "BookmarksNavigationControllerDelegate.h"
#import "RotatablePopoverControllerDelegate.h"
#import <UIKit/UIView.h>

@class BookmarksBarChevronButton, NSMutableArray, WebBookmark, BookmarksNavigationController, UIButton;

__attribute__((visibility("hidden")))
@interface BookmarksBarView : UIView <BookmarksNavigationControllerDelegate, RotatablePopoverControllerDelegate> {
	NSMutableArray* _bookmarkBarLabels;
	unsigned _bookmarkBarID;
	BookmarksBarChevronButton* _moreBookmarksButton;
	WebBookmark* _moreBookmarksParent;
	unsigned _moreBookmarksOffset;
	UIButton* _buttonUsedToShowNavigationController;
	BOOL _isShowingNavigationController;
	BookmarksNavigationController* _bookmarksNavigationController;
	BOOL _usesPrivateBrowsingStyle;
}
@property(assign, nonatomic) BOOL usesPrivateBrowsingStyle;
-(void)bookmarksNavigationControllerDidReload:(id)bookmarksNavigationController;
-(void)bookmarksNavigationControllerReloadDidFail:(id)bookmarksNavigationControllerReload;
-(id)containingBookmarkForNavigationController:(id)navigationController;
-(void)goToHistoryURL:(id)historyURL;
-(void)goToBookmark:(id)bookmark;
-(void)closeBrowserPanel:(id)panel;
-(void)browserPanel:(id)panel didChangeState:(int)state;
-(void)didHideBrowserPanel:(id)panel;
-(void)willHideBrowserPanel:(id)panel;
-(void)didShowBrowserPanel:(id)panel;
-(void)willShowBrowserPanel:(id)panel;
-(id)browserPanel;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
-(void)_receivedBookmarksChangedNotification:(id)notification;
-(void)_reloadBookmarkLabels;
-(void)_createAllLabelButtons;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)popoverController:(id)controller willPresentAfterRotationToInterfaceOrientation:(int)interfaceOrientation;
-(void)_dismissCurrentBookmarksPopover;
-(void)_buttonTapped:(id)tapped;
-(void)_touchDownInButton:(id)button;
-(void)_clearBookmarksNavigationController;
-(void)_setButtonUsedToShowNavigationController:(id)showNavigationController;
@end

