/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class BookmarksBarLabelGradientView, UIImage, UIColor, UIFont, NSString;

__attribute__((visibility("hidden")))
@interface BookmarksBarLabel : UIView {
	UIImage* gradientImage;
	UIImage* highlightGradientImage;
	BOOL isHightlighted;
	NSString* text;
	UIFont* font;
	UIColor* textColor;
	UIColor* shadowColor;
	CGSize shadowOffset;
	BookmarksBarLabelGradientView* gradientView;
}
@property(assign) CGSize shadowOffset;
@property(retain) UIColor* shadowColor;
@property(retain) UIColor* textColor;
@property(retain) UIFont* font;
@property(retain) NSString* text;
@property(retain) UIImage* highlightGradientImage;
@property(retain) UIImage* gradientImage;
-(void)drawRect:(CGRect)rect;
-(void)setHighlighted:(BOOL)highlighted;
-(BOOL)isHightlighted;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
@end

