/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BrowserPanel.h"
#import <UIKit/UINavigationController.h>
#import "UINavigationBarDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "MobileSafari-Structs.h"
#import "UIActionSheetDelegate.h"

@class NSArray, BookmarkInfoViewController, NSTimer, WebBookmarkCollection, NSString, UIActionSheet, UIBarButtonItem, UISegmentedControl, NSMutableDictionary;
@protocol BookmarksNavigationControllerDelegate;

__attribute__((visibility("hidden")))
@interface BookmarksNavigationController : UINavigationController <BrowserPanel, UINavigationBarDelegate, UINavigationControllerDelegate, UIActionSheetDelegate> {
	BookmarkInfoViewController* _bookmarkInfoViewController;
	WebBookmarkCollection* _bookmarkCollection;
	NSTimer* _bookmarkSyncTimer;
	BOOL _isVisible;
	BOOL _shouldSavePlaceInBookmarks;
	BOOL _restoringPlaceInBookmarks;
	id<BookmarksNavigationControllerDelegate> _bookmarksDelegate;
	int _panelState;
	UIActionSheet* _clearHistoryAlertSheet;
	BOOL _allowsEditing;
	UIBarButtonItem* _clearHistoryItem;
	UIBarButtonItem* _doneItem;
	UIBarButtonItem* _editItem;
	UIBarButtonItem* _emptySpaceItem;
	UIBarButtonItem* _newFolderItem;
	BOOL _showCollections;
	UISegmentedControl* _collectionSegmentedControl;
	UIBarButtonItem* _collectionBarItem;
	NSArray* _collectionToolbarItems;
	NSArray* _collectionsParentedInBookmarks;
	NSArray* _topLevelCollections;
	NSString* _currentCollection;
	NSMutableDictionary* _savedCollectionState;
}
@property(assign, nonatomic) id bookmarksDelegate;
@property(assign, nonatomic) BOOL allowsEditing;
-(void)dealloc;
-(void)_clearBookmarkSyncTimer;
-(void)_bookmarkSyncTimerDidFire:(id)_bookmarkSyncTimer;
-(BOOL)shouldHideOnSuspend;
-(BOOL)shouldResumePanel;
-(void)panelWillSuspend;
-(BOOL)shouldShowButtonBar;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)pausesPages;
-(int)panelState;
-(int)panelType;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)navigationController:(id)controller willShowViewController:(id)controller2 animated:(BOOL)animated;
-(void)_restoreCurrentCollectionState;
-(void)_restorePanelState;
-(void)_savePanelState;
-(void)_loadSavedPanelState;
-(void)setCurrentCollection:(id)collection;
-(id)newRootViewControllerForCollection:(id)collection;
-(void)_selectedCollectionChanged:(id)changed;
-(id)localizedTitleForCollection:(id)collection;
-(id)segmentedControlItemForCollection:(id)collection;
-(void)_setupCollections;
-(id)collectionsParentedInBookmarks;
-(BOOL)rebaseOnAncestorBookmark:(id)bookmark skipOffset:(unsigned)offset;
-(BOOL)rebaseOnDescendentBookmark:(id)bookmark;
-(void)updatePanelForTabDocument:(id)tabDocument;
-(void)bookmarkSourceContentsChanged:(id)changed;
-(void)_updateClearHistoryButton;
-(id)toolbarItems;
-(void)_createToolbarItems;
-(void)showLockedBookmarksDatabaseAlertForBookmarkAddition:(BOOL)bookmarkAddition;
-(void)createNewFolder;
-(void)showInfoForBookmark:(id)bookmark inFolderNamed:(id)folderNamed;
-(void)removeAllHistoryItems;
-(void)edit;
-(void)done;
-(void)close;
-(void)setPanelState:(int)state;
-(void)reloadViewControllers;
-(BOOL)_inEditMode;
-(BOOL)_isEditingPanelState:(int)state;
-(void)_popFromKeyboardReturn;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(id)rotatingFooterView;
-(void)_getRotationContentSettings:(XXStruct_3uUjXA*)settings;
-(void)viewWillLayoutSubviews;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)setRootBookmark:(id)bookmark skipOffset:(unsigned)offset;
-(id)rootBookmark;
-(id)topmostStateRestoringViewController;
-(id)topCloudTabViewController;
-(id)topReadingListViewController;
-(id)topBookmarksTableViewController;
-(id)topHistoryTableViewController;
-(id)initWithBookmarksDelegate:(id)bookmarksDelegate topBookmark:(id)bookmark skipOffset:(int)offset;
-(id)initWithBookmarksDelegate:(id)bookmarksDelegate topBookmark:(id)bookmark;
@end

