/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITableViewDataSource.h"
#import <UIKit/UIViewController.h>
#import "UITableViewDelegate.h"
#import "MobileSafari-Structs.h"

@class BookmarkTextEntryTableViewCell, UITableView, NSString;
@protocol BookmarkTextEntryTableViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface BookmarkTextEntryTableViewController : UIViewController <UITableViewDelegate, UITableViewDataSource> {
	id<BookmarkTextEntryTableViewControllerDelegate> _delegate;
	NSString* _initialText;
	int _autoCapsType;
	UITableView* _table;
	BookmarkTextEntryTableViewCell* _textEntryCell;
}
-(void)dealloc;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)layoutViews;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)loadView;
-(id)initWithBookmarkInfoViewField:(int)bookmarkInfoViewField text:(id)text autoCapsType:(int)type delegate:(id)delegate;
@end

