/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class BookmarksBarLabel;

__attribute__((visibility("hidden")))
@interface BookmarksBarLabelGradientView : UIView {
	BookmarksBarLabel* parentLabel;
}
@property(assign) BookmarksBarLabel* parentLabel;
-(void)drawRect:(CGRect)rect;
@end

