/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BookmarksPanelStateRestoring.h"
#import "PopoverSizingTableViewController.h"

@class WebBookmark, NSIndexPath, WebBookmarkList, WebBookmarkCollection, UIBarButtonItem, NSString;

__attribute__((visibility("hidden")))
@interface BookmarksTableViewController : PopoverSizingTableViewController <BookmarksPanelStateRestoring> {
	UIBarButtonItem* _bookmarksEditDoneButtonItem;
	UIBarButtonItem* _bookmarksNewFolderButtonItem;
	NSIndexPath* _chosenCellIndexPath;
	WebBookmark* _chosenBookmark;
	WebBookmarkCollection* _collection;
	WebBookmarkList* _bookmarkList;
	WebBookmark* _folder;
	unsigned _skipOffset;
	float _restoredScrollPosition;
}
@property(readonly, assign, nonatomic) NSString* collectionType;
@property(retain, nonatomic) WebBookmark* folder;
@property(readonly, assign, nonatomic) unsigned folderID;
-(void)restoreScrollPosition:(float)position;
-(float)currentScrollPosition;
-(BOOL)restoreStateWithDictionary:(id)dictionary;
-(id)currentStateDictionary;
-(id)tableView:(id)view targetIndexPathForMoveFromRowAtIndexPath:(id)indexPath toProposedIndexPath:(id)proposedIndexPath;
-(int)tableView:(id)view editingStyleForRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didEndEditingRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view willBeginEditingRowAtIndexPath:(id)indexPath;
-(void)_leaveSwipeToDeleteMode;
-(BOOL)tableView:(id)view shouldIndentWhileEditingRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view moveRowAtIndexPath:(id)indexPath toIndexPath:(id)indexPath3;
-(BOOL)tableView:(id)view canMoveRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(BOOL)tableView:(id)view canEditRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view willSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)_bookmarkAtIndexPath:(id)indexPath;
-(int)_bookmarkListIndexFromIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(unsigned)_numberOfRowsInsertedBeforeRootBookmarks;
-(id)_collectionForRowAtIndexPath:(id)indexPath;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)_newFolder;
-(void)_done;
-(void)cancelCurrentEdit;
-(void)_toggleEditing;
-(void)setEditing:(BOOL)editing animated:(BOOL)animated;
-(id)bookmarksNavigationController;
-(void)dealloc;
-(void)reloadBookmarks;
-(void)_recreateBookmarkList;
-(BOOL)_inRootFolder;
-(id)initWithFolder:(id)folder inCollection:(id)collection skipOffset:(unsigned)offset;
-(id)initWithFolder:(id)folder inCollection:(id)collection;
@end

