/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>
#import "UITextFieldDelegate.h"
#import "MobileSafari-Structs.h"

@class UITextField;

__attribute__((visibility("hidden")))
@interface BookmarkTextEntryTableViewCell : UITableViewCell <UITextFieldDelegate> {
	UITextField* _textField;
}
-(void)dealloc;
-(id)textField;
-(void)setUserInteractionEnabled:(BOOL)enabled;
-(void)setHighlighted:(BOOL)highlighted animated:(BOOL)animated;
-(BOOL)textFieldShouldReturn:(id)textField;
-(BOOL)textFieldShouldBeginEditing:(id)textField;
-(void)layoutSubviews;
-(id)initWithText:(id)text autoCapsType:(int)type;
@end

