/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "FolderPickerViewControllerDelegate.h"
#import "BookmarkTextEntryTableViewControllerDelegate.h"
#import <UIKit/UIViewController.h>
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSObject, WebBookmark, UITableViewCell, BookmarkTextEntryTableViewCell, WebBookmarkCollection, UITableView;
@protocol BookmarkInfoViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface BookmarkInfoViewController : UIViewController <FolderPickerViewControllerDelegate, BookmarkTextEntryTableViewControllerDelegate, UITableViewDataSource, UITableViewDelegate> {
	WebBookmarkCollection* _collection;
	WebBookmark* _bookmark;
	WebBookmark* _parentBookmark;
	BOOL _addingBookmark;
	UITableView* _table;
	BookmarkTextEntryTableViewCell* _titleCell;
	BookmarkTextEntryTableViewCell* _addressCell;
	UITableViewCell* _folderCell;
	int _editingField;
	BOOL _didSelectFolder;
	NSObject<BookmarkInfoViewControllerDelegate>* _delegate;
}
@property(assign, nonatomic) NSObject<BookmarkInfoViewControllerDelegate>* delegate;
-(void)viewWillLayoutSubviews;
-(CGSize)contentSizeForViewInPopoverView;
-(void)dealloc;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)bookmarkTextEntryTableViewController:(id)controller dismissedWithText:(id)text;
-(void)folderPicker:(id)picker pickedFolder:(id)folder;
-(void)_valuesChanged;
-(BOOL)isEditingField;
-(void)_showFolderPicker;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)_editField:(int)field;
-(BOOL)canSaveChanges;
-(void)saveChanges;
-(void)setParent:(id)parent;
-(void)setBookmark:(id)bookmark;
-(void)_updateCellValues;
-(void)_updateParentFolderCell;
-(BOOL)titleCellHasText;
-(id)bookmark;
-(void)_bookmarksDidReload;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(id)_titleCell;
-(void)layoutViews;
-(void)scrollViewDidEndScrollingAnimation:(id)scrollView;
-(void)_adjustContentInsetForKeyboardNotification:(id)keyboardNotification;
-(BOOL)shouldShowButtonBar;
-(void)loadView;
-(void)_createCellsIfNeeded;
-(void)_addressDidEndEditing;
-(void)_titleDidEndEditing;
-(void)_popFromKeyboardReturn;
-(void)_cancel;
-(void)_save;
-(id)initWithBookmark:(id)bookmark inCollection:(id)collection addingBookmark:(BOOL)bookmark3;
@end

