/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "BookmarksBarButton.h"

@class UIImageView;

__attribute__((visibility("hidden")))
@interface BookmarksBarChevronButton : BookmarksBarButton {
	UIImageView* _chevronImageView;
}
-(void)dealloc;
-(void)setUsesHighlightedStyle:(BOOL)style;
-(void)layoutSubviews;
-(void)setUsesPrivateBrowsingStyle:(BOOL)style;
-(id)initWithFrame:(CGRect)frame;
@end

