/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIButton.h>


__attribute__((visibility("hidden")))
@interface BookmarksBarButton : UIButton {
	BOOL _usesHighlightedStyle;
	BOOL _usesPrivateBrowsingStyle;
}
-(void)setSelected:(BOOL)selected;
-(void)setHighlighted:(BOOL)highlighted;
-(BOOL)_shouldShowHighlightedStyleImages;
-(BOOL)usesHighlightedStyle;
-(void)setUsesHighlightedStyle:(BOOL)style;
-(id)initWithFrame:(CGRect)frame;
@end

