/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIViewController.h>
#import "MobileSafari-Structs.h"


__attribute__((visibility("hidden")))
@interface BrowserRootViewController : UIViewController {
	int _lastKnownOrientation;
}
@property(assign, nonatomic) int lastKnownOrientation;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)_getRotationContentSettings:(XXStruct_3uUjXA*)settings;
-(id)rotatingFooterView;
-(id)rotatingHeaderView;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(id)init;
@end

