/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BrowserPanel.h"
#import <Foundation/NSObject.h>
#import "RotatablePopoverControllerDelegate.h"

@class BrowserICSPreviewPanelNavController, OpenInOtherAppActivityViewController, EKICSPreviewController, RotatablePopoverController, NSString;

__attribute__((visibility("hidden")))
@interface BrowserICSPreviewPanel : NSObject <RotatablePopoverControllerDelegate, BrowserPanel> {
	OpenInOtherAppActivityViewController* _activityViewController;
	BrowserICSPreviewPanelNavController* _wrappingNavController;
	RotatablePopoverController* _activityPopover;
	EKICSPreviewController* _icsController;
	NSString* _filePath;
}
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(BOOL)shouldHideOnSuspend;
-(int)pausesPages;
-(int)panelState;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)panelType;
-(id)viewController;
-(void)_done:(id)done;
-(void)_openInOtherAppsButtonPressed:(id)otherAppsButtonPressed;
-(id)activityViewController;
-(void)dealloc;
-(id)initWithFilePath:(id)filePath;
@end

