/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol BrowserPanel <NSObject>
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)pausesPages;
-(int)panelState;
-(int)panelType;
@optional
-(BOOL)shouldShowToolbarInFullscreen;
-(BOOL)shouldResumePanel;
-(void)panelWillSuspend;
-(id)toolbarItems;
@end

