/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "UIWebViewDelegate.h"
#import "RotatablePopoverControllerDelegate.h"
#import <UIKit/UIView.h>

@class NSMutableArray, UIWebView, ReaderContext, ReaderWebView, UIButton, UIControl, UIImageView;

__attribute__((visibility("hidden")))
@interface BrowserReaderView : UIView <RotatablePopoverControllerDelegate, UIWebViewDelegate> {
	ReaderWebView* _webContentView;
	ReaderContext* _readerContext;
	UIControl* _fadeView;
	UIImageView* _fadeTopView;
	UIImageView* _fadeBottomView;
	UIButton* _fontButton;
	UIView* _headerView;
	UIButton* _doneButton;
	UIButton* _actionButton;
	UIView* _singleLineView;
	NSMutableArray* _shadows;
	BOOL _isAnimating;
	UIView* _fontButtonClipperView;
	UIView* _bottomFadeClipperView;
	int _savedStatusBarStyle;
}
@property(readonly, assign, nonatomic) UIWebView* webView;
-(void)uiWebView:(id)view didClearWindowObject:(id)object forFrame:(id)frame;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(void)adoptFullScreenScrollToTopIndicatorView:(id)topIndicatorView;
-(int)topScrollOffset;
-(void)_setAnimating:(BOOL)animating;
-(void)_updateBackgroundShadows;
-(void)_initBackgroundShadows;
-(void)_initTopAndBottomFades;
-(void)_actionButtonClicked;
-(void)popoverControllerDidDismissPopover:(id)popoverController;
-(void)popoverController:(id)controller willPresentAfterRotationToInterfaceOrientation:(int)interfaceOrientation;
-(void)_showFontPopoverControl;
-(CGRect)_fontPopoverPresentationRect;
-(void)updateSubviews;
-(void)_setScrollIndicatorInset:(float)inset contentInset:(float)inset2;
-(CGRect)_frameForWebContentView;
-(float)_defaultContentViewWidth;
-(void)_fadeTapped;
-(void)_cancel;
-(void)_removeAnimationFinished;
-(void)_slideInAnimationFinished;
-(void)didHideTabExposeView;
-(void)willHideTabExposeViewWithDuration:(double)duration;
-(void)didShowTabExposeView;
-(void)willShowTabExposeViewWithDuration:(double)duration;
-(void)_hideWebViewAndShadowViews:(BOOL)views;
-(void)didAnimateRotate;
-(void)willAnimateRotate;
-(void)_showInnerShadowsAndClipBottomFade:(BOOL)fade;
-(void)removeFromSuperview:(BOOL)superview;
-(void)showAboveView:(id)view animated:(BOOL)animated;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame readerContext:(id)context;
@end

