/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UINavigationController.h>

@class BrowserICSPreviewPanel, UIBarButtonItem;

__attribute__((visibility("hidden")))
@interface BrowserICSPreviewPanelNavController : UINavigationController {
	UIBarButtonItem* _doneBarButtonItem;
	UIBarButtonItem* _activitiesBarButtonItem;
	BrowserICSPreviewPanel* _icsPanel;
	BOOL _closeBrowserPanelAlreadyCalled;
}
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(id)popViewControllerAnimated:(BOOL)animated;
-(void)_updateNavigationBarItems;
-(void)_ensureRightBarButtonItemsIncludesDoneItem:(id)item;
-(void)_ensureLeftBarButtonItemsIncludesDoneItem:(id)item;
-(void)_ensureLeftBarButtonItemsIncludesActivitiesItem:(id)item;
-(id)_doneBarButonItem;
-(id)_activtyBarButtonItem;
-(void)setCloseBrowserPanelAlreadyCalled:(BOOL)called;
-(void)setOwningPanel:(id)panel;
-(void)dealloc;
@end

