/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSURL;

__attribute__((visibility("hidden")))
@interface CaptiveLandingPageController : NSObject {
	NSURL* _captiveLandingPageURL;
	unsigned long long _URLGeneration;
}
@property(readonly, assign, nonatomic) NSURL* captiveLandingPageURL;
+(id)sharedCaptiveLandingPageController;
-(void)clearCaptiveLandingPageURL;
-(id)popCaptiveLandingPageURL;
-(void)dealloc;
-(id)init;
@end

