/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BrowserPanel.h"
#import <UIKit/UINavigationController.h>


__attribute__((visibility("hidden")))
@interface CloudTabNavigationController : UINavigationController <BrowserPanel> {
}
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(BOOL)handlesAnimations;
-(int)pausesPages;
-(int)panelState;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)panelType;
-(id)initWithDelegate:(id)delegate;
@end

