/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, NSURL, NSDictionary;

__attribute__((visibility("hidden")))
@interface CloudTab : NSObject {
	NSDictionary* _readerScrollPositionDictionary;
	BOOL _isShowingReader;
	NSURL* _URL;
	NSString* _title;
}
@property(copy, nonatomic) NSDictionary* readerScrollPositionDictionary;
@property(assign, nonatomic) BOOL isShowingReader;
@property(copy, nonatomic) NSURL* URL;
@property(copy, nonatomic) NSString* title;
-(id)description;
-(void)dealloc;
-(id)_dictionaryRepresentation;
-(id)_initWithDictionary:(id)dictionary;
@end

