/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIViewController.h>
#import "BookmarksPanelStateRestoring.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class EmptyCollectionExplanationView, NSArray, NSTimer, NSString, UITableView;
@protocol CloudTabNavigationControllerDelegate;

__attribute__((visibility("hidden")))
@interface CloudTabViewController : UIViewController <BookmarksPanelStateRestoring, UITableViewDataSource, UITableViewDelegate> {
	id<CloudTabNavigationControllerDelegate> _delegate;
	NSArray* _devices;
	NSTimer* _refreshTimer;
	EmptyCollectionExplanationView* _explanationView;
	UITableView* _tableView;
	float _restoredScrollPosition;
}
@property(readonly, assign, nonatomic) NSString* collectionType;
-(void)restoreScrollPosition:(float)position;
-(float)currentScrollPosition;
-(BOOL)restoreStateWithDictionary:(id)dictionary;
-(id)currentStateDictionary;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(id)_cloudTabNavigationController;
-(void)_refreshTimerDidFire:(id)_refreshTimer;
-(void)_clearRefreshTimer;
-(id)_tabForIndexPath:(id)indexPath;
-(void)_reloadDevicesAndTable;
-(void)_loadDevices;
-(CGSize)contentSizeForViewInPopoverView;
-(void)_updatePopoverSize;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)_done;
-(void)_adjustTableViewInsetsForOrientation:(int)orientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(id)_bookmarksNavigationController;
-(void)_clearExplanationView;
-(void)_setupExplanationView;
-(void)loadView;
-(void)dealloc;
-(id)initWithDelegate:(id)delegate;
@end

