/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface DebugUtilities : NSObject {
	int sampleToolProcessID;
	int sampleToolPtyFD;
	int sharkToolProcessID;
	NSString* sampleToolOutputPath;
	NSString* sharkToolOutputBase;
}
+(id)sharedDebugUtilities;
-(BOOL)stopSharkTool;
-(BOOL)startSharkTool;
-(BOOL)startSharkToolWithIdentifier:(id)identifier;
-(void)setSharkToolOutputBase:(id)base;
-(BOOL)stopSampleTool;
-(BOOL)startSampleTool;
-(BOOL)startSampleToolWithIdentifier:(id)identifier;
-(void)setSampleToolOutputPath:(id)path;
-(void)dealloc;
@end

