/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@protocol BackgroundDrawing;

__attribute__((visibility("hidden")))
@interface EllipsedTextFadeView : UIView {
	float _fadeAdjustment;
	UIView<BackgroundDrawing>* _backgroundView;
}
@property(assign, nonatomic) UIView<BackgroundDrawing>* backgroundView;
@property(assign, nonatomic) float fadeAdjustment;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)drawRect:(CGRect)rect;
@end

