/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class UIImage, NSString;

__attribute__((visibility("hidden")))
@interface EmptyCollectionLabel : UIView {
	NSString* _text;
	CTFramesetterRef _framesetter;
	CGSize _textSizePortrait;
	CGSize _textSizeLandscape;
	UIImage* _replacementImage;
	unsigned _replacementLocation;
}
-(void)dealloc;
-(void)drawRect:(CGRect)rect;
-(CGSize)sizeForOrientation:(int)orientation;
-(id)initWithFrame:(CGRect)frame text:(id)text font:(id)font replacingString:(id)string withImage:(id)image;
@end

