/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class EmptyCollectionLabel, UIImageView;

__attribute__((visibility("hidden")))
@interface EmptyCollectionExplanationView : UIView {
	UIImageView* _imageView;
	EmptyCollectionLabel* _explanationLabel;
	EmptyCollectionLabel* _instructionsLabel;
	int _interfaceOrientation;
}
@property(assign, nonatomic) int interfaceOrientation;
-(void)layoutSubviews;
-(float)_paddingBetweenImageAndText;
-(void)fadeOutAnimated:(BOOL)animated completion:(id)completion;
-(void)fadeInAnimated:(BOOL)animated;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame image:(id)image explanationText:(id)text instructionsText:(id)text4 replacingString:(id)string withImage:(id)image6;
@end

