/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UISearchField.h>

@class UIImageView;

__attribute__((visibility("hidden")))
@interface ExtendedSearchField : UISearchField {
	BOOL _isBecomingFirstResponder;
	BOOL forceDrawingPlaceholder;
	CGRect _editRectOverride;
	UIImageView* _privateBrowsingBackgroundView;
}
@property(readonly, assign, nonatomic) BOOL isBecomingFirstResponder;
-(CGRect)editingRectForBounds:(CGRect)bounds;
-(CGRect)textRectForBounds:(CGRect)bounds;
-(void)setUsesPrivateBrowsingStyle:(BOOL)style;
-(void)layoutSubviews;
-(BOOL)drawingPlaceholderOnly;
-(void)setForceDrawingPlaceholder:(BOOL)placeholder;
-(void)setFrame:(CGRect)frame forEditing:(BOOL)editing;
-(BOOL)becomeFirstResponder;
-(BOOL)canBecomeFirstResponder;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

