/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface FadeView : UIView {
	id _target;
	SEL _action;
}
@property(assign, nonatomic) SEL action;
@property(assign, nonatomic) id target;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(id)initWithFrame:(CGRect)frame;
@end

