/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "UIKeyInput.h"
#import "BrowserPanel.h"
#import <UIKit/UIView.h>

@class NSMutableArray, NSArray, FindOnPageSegmentedControl, FindOnPageToolbar, UIActivityIndicatorView, UILabel;

__attribute__((visibility("hidden")))
@interface FindOnPagePanel : UIView <BrowserPanel, UIKeyInput> {
	CGRect _highlightedRect;
	NSMutableArray* _highlightBubbleViews;
	FindOnPageToolbar* _accessory;
	BOOL _requiresKeyboard;
	NSArray* _toolbarItems;
	UILabel* _currentResultLabel;
	FindOnPageSegmentedControl* _previousNextControl;
	UIActivityIndicatorView* _indicatorView;
	BOOL _useActivityView;
	NSArray* _pdfHighlightViews;
}
@property(assign, nonatomic, getter=isSecureTextEntry) BOOL secureTextEntry;
@property(assign, nonatomic) BOOL enablesReturnKeyAutomatically;
@property(assign, nonatomic) int returnKeyType;
@property(assign, nonatomic) int keyboardAppearance;
@property(assign, nonatomic) int keyboardType;
@property(assign, nonatomic) int spellCheckingType;
@property(assign, nonatomic) int autocorrectionType;
@property(assign, nonatomic) int autocapitalizationType;
@property(assign, nonatomic) BOOL useActivityView;
+(BOOL)expandedRectsWouldIntersect:(id)intersect;
-(void)dealloc;
-(void)deleteBackward;
-(void)insertText:(id)text;
-(BOOL)hasText;
-(BOOL)canBecomeFirstResponder;
-(void)setRequiresKeyboard:(BOOL)keyboard;
-(BOOL)_requiresKeyboardWhenFirstResponder;
-(void)updateUI;
-(id)findTextField;
-(id)inputAccessoryView;
-(void)setHighlightBubbleHidden:(BOOL)hidden;
-(void)setSelectionRect:(CGRect)rect textRects:(id)rects contentViews:(id)views wobble:(BOOL)wobble;
-(void)setSelectionRect:(CGRect)rect textRects:(id)rects contentImage:(CGImageRef)image wobble:(BOOL)wobble;
-(void)_setSelectionRect:(CGRect)rect textRects:(id)rects contentImage:(CGImageRef)image contentViews:(id)views wobble:(BOOL)wobble;
-(void)clearHighlightViews;
-(void)_addContentViewAtIndex:(unsigned)index withRect:(CGRect)rect;
-(id)initWithFrame:(CGRect)frame;
-(id)toolbarItems;
-(void)_findOnPageSegmentedControlValueChanged:(id)changed;
-(void)_done;
-(BOOL)shouldShowToolbarInFullscreen;
-(BOOL)shouldHideOnSuspend;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)pausesPages;
-(int)panelState;
-(int)panelType;
-(id)_currentResultLabel;
-(BOOL)_willShowActivityIndicator;
@end

