/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class WebBookmark;

__attribute__((visibility("hidden")))
@interface FolderPickerItem : NSObject {
	WebBookmark* _bookmark;
	int _depth;
}
-(id)icon;
-(id)title;
-(unsigned)depth;
-(id)bookmark;
-(void)dealloc;
-(id)initWithBookmark:(id)bookmark depth:(unsigned)depth;
@end

