/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>


__attribute__((visibility("hidden")))
@interface HighlightBubbleView : UIView {
	CGImageRef _highlightedContent;
	CGPoint _highlightedContentOrigin;
}
-(id).cxx_construct;
-(void)dealloc;
-(void)setHighlightedContent:(CGImageRef)content withOrigin:(CGPoint)origin;
-(void)drawRect:(CGRect)rect;
@end

