/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BookmarksPanelStateRestoring.h"
#import "PopoverSizingTableViewController.h"

@class NSCalendarDate, NSString;

__attribute__((visibility("hidden")))
@interface HistoryTableViewController : PopoverSizingTableViewController <BookmarksPanelStateRestoring> {
	NSCalendarDate* _date;
	float _restoredScrollPosition;
}
@property(readonly, assign, nonatomic) NSString* collectionType;
-(void)restoreScrollPosition:(float)position;
-(float)currentScrollPosition;
-(BOOL)restoreStateWithDictionary:(id)dictionary;
-(id)currentStateDictionary;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)_clearHistory;
-(void)updateClearHistoryButtonEnable;
-(void)_done;
-(id)bookmarksNavigationController;
-(void)dealloc;
-(id)date;
-(id)initForHistoryRoot;
-(id)initWithCalendarDate:(id)calendarDate;
-(void)historyChangedDestructively:(id)destructively;
-(void)historyChanged:(id)changed;
-(id)_stringForCalendarDate:(id)calendarDate;
@end

