/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class WebHistory;

__attribute__((visibility("hidden")))
@interface History : NSObject {
	WebHistory* _webHistory;
	BOOL _savePending;
	BOOL _isMergedWithSavedHistory;
}
+(id)sharedHistory;
+(id)historyURL;
-(void)savePendingChanges;
-(id)titleForItem:(id)item;
-(id)itemAtIndex:(unsigned)index fromDate:(id)date;
-(unsigned)numberOfItemsFromDate:(id)date;
-(id)_topLevelItems;
-(unsigned)_recentCount;
-(void)clearHistory;
-(id)webHistory;
-(void)mergeWithSavedHistoryIfNecessary;
-(void)dealloc;
-(id)init;
-(id)_stringForCalendarDate:(id)calendarDate;
-(void)receivedEntriesChangedNotification:(id)notification;
-(void)_registerForHistoryNotifications;
@end

