/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface MSFlipAnimation : NSObject {
	int _transitionSide;
	float _duration;
	UIView* _containerView;
	UIView* _parentView;
	UIView* _fromView;
	UIView* _toView;
	id _beginBlock;
	id _completion;
}
@property(copy, nonatomic) id completion;
@property(copy, nonatomic) id beginBlock;
@property(retain, nonatomic) UIView* toView;
@property(retain, nonatomic) UIView* fromView;
@property(retain, nonatomic) UIView* parentView;
@property(assign, nonatomic) float duration;
@property(assign, nonatomic) int transitionSide;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)_rotateLayer:(id)layer byAngle:(float)angle completion:(id)completion;
-(void)_cleanupTransition;
-(void)_performTransition;
-(void)_prepareTransition;
-(void)performAnimation;
-(void)dealloc;
@end

