/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSHTTPCookieStorage.h>


@interface NSHTTPCookieStorage (Extras)
-(void)deleteAllCookies;
-(void)deleteCookiesForDomain:(id)domain;
-(id)newDomainDiskUsageDictionary;
-(unsigned long long)_diskUsageForCookie:(id)cookie;
@end

