/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActivityItemsSource.h"
#import <Foundation/NSObject.h>

@class NSURL;

__attribute__((visibility("hidden")))
@interface OpenInOtherAppActivityItemsSource : NSObject <UIActivityItemsSource> {
	NSURL* _fileURL;
}
-(id)activityViewController:(id)controller itemsForActivityType:(id)activityType;
-(id)activityViewControllerPlaceholderItems:(id)items;
-(void)dealloc;
-(id)initWithFilePath:(id)filePath;
@end

