/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIBarButtonItem.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface OpenInApplicationBarButtonItem : UIBarButtonItem {
	NSString* _applicationIdentifier;
}
@property(copy, nonatomic) NSString* applicationIdentifier;
-(void)dealloc;
@end

