/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "LSOpenResourceOperationDelegate.h"
#import <UIKit/UIActivity.h>

@class LSApplicationProxy, NSString;

__attribute__((visibility("hidden")))
@interface OpenWithAppUIActivity : UIActivity <LSOpenResourceOperationDelegate> {
	LSApplicationProxy* _appProxy;
	NSString* _filePath;
}
-(void)openResourceOperation:(id)operation didFinishCopyingResource:(id)resource;
-(void)performActivity;
-(BOOL)canPerformWithActivityItems:(id)activityItems;
-(id)_activityImage;
-(id)activityTitle;
-(id)activityType;
-(void)dealloc;
-(id)initWithApplicationIdentifier:(id)applicationIdentifier andFilePath:(id)path;
@end

