/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface PageLoadTestLogger : NSObject {
	sFILE* _out;
	sFILE* _outfile;
	BOOL _waitUntilDone;
	unsigned _headerLen;
}
-(void)pageLoadTestRunnerFinishedTest:(id)test;
-(void)pageLoadTestRunnerFinishedPageLoad:(id)load;
-(void)outputToFile:(id)file waitUntilDone:(BOOL)done;
-(void)_printPageLoadStatistics:(id)statistics forURL:(id)url maxURLLength:(unsigned)length;
-(void)dealloc;
-(id)init;
@end

