/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <Foundation/NSObject.h>

@class PageLoadTestLogger, PageLoadStatistics, NSMutableArray;

__attribute__((visibility("hidden")))
@interface PageLoadTestRunner : NSObject {
	NSObject* delegate;
	PageLoadTestLogger* testLogger;
	PageLoadStatistics* statistics;
	BOOL running;
	NSMutableArray* commands;
	NSMutableArray* pageLoadArray;
	int repetitions;
	unsigned currentPage;
	int currentRepetition;
	BOOL goingBack;
	int pagesTimed;
	double totalSquareRootsOfTime;
	int cacheClearDirective;
	int profilingDirective;
	BOOL checkForWorldLeaks;
	BOOL disableProgressBar;
	double savedDefaultTimeoutInterval;
}
+(XXStruct_Eg7cJC)heapStatistics;
+(id)worldLeaksString;
+(BOOL)closingBrowserWindowsForWorldLeakTest;
+(void)addLeakToArray:(id)array count:(int)count name:(id)name;
-(void)setCurrentPage:(int)page;
-(void)setCheckForWorldLeaks:(BOOL)worldLeaks;
-(XXStruct_Eg7cJC)heapDelta;
-(XXStruct_Eg7cJC)heapAfter;
-(XXStruct_Eg7cJC)heapBefore;
-(int)currentRepetition;
-(int)repetitions;
-(void)setRepetitions:(int)repetitions;
-(void)pageReaderDetectionDone:(id)done;
-(void)pageLoadPossiblyDone:(id)done;
-(void)pageLoadPossiblyStarted:(id)started;
-(void)readerDetectionDone:(id)done;
-(void)pageLoadDone:(id)done;
-(void)pageLoadStarted;
-(int)cacheClearDirective;
-(void)setCacheClearDirective:(int)directive;
-(float)meanRenderFps;
-(double)meanRenderTime;
-(double)squareMeanRootTime;
-(double)meanTime;
-(void)addPageLoadTotals:(id)totals;
-(void)stop;
-(void)startGoBackTest;
-(void)start;
-(void)startTest;
-(void)resetPageLoads;
-(void)setProfilingDirective:(int)directive;
-(void)unpause;
-(void)pause;
-(BOOL)canGoToPreviousPage;
-(BOOL)canGoToNextPage;
-(void)goToPreviousPage;
-(void)goToNextPage;
-(void)goBack;
-(void)repetitionDone;
-(void)testDone;
-(BOOL)checkForWorldLeaksNow;
-(void)checkForWorldLeaksSoon;
-(void)closeBrowserWindowsAndFinishCheckingForWorldLeaks;
-(BOOL)finishCheckingForWorldLeaks;
-(void)closeBrowserWindows;
-(void)goToPage;
-(void)clearCacheWithURL:(id)url;
-(BOOL)running;
-(id)currentPageLoad;
-(id)pageLoadArray;
-(void)setDelegate:(id)delegate;
-(id)delegate;
-(void)dealloc;
-(id)statistics;
-(id)initForPLT2Suite:(id)plt2Suite;
-(id)init;
-(bool)loadTestSuiteFile:(id)file;
-(bool)loadBundleTestSuiteFile:(id)file;
-(bool)loadTestSuite:(id)suite;
-(void)runTestCommands:(id)commands;
-(void)runOneCommand;
-(void)setSingleTestURL:(id)url;
-(void)setTestLogger:(id)logger;
-(id)testLogger;
@end

