/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RotatableBrowserPanel.h"
#import "MobileSafari-Structs.h"
#import "UIScrollViewDelegate.h"
#import <UIKit/UIView.h>

@class NSArray, UIScrollView, TabDocument, NSObject, TabScrollIndicatorContainerView, PagedTabExposeHitTestingView, UIPageControl, UIImageView, UILabel, UIBarButtonItem, NSMutableArray;
@protocol TabExposeDelegate;

__attribute__((visibility("hidden")))
@interface PagedTabExposeView : UIView <UIScrollViewDelegate, RotatableBrowserPanel> {
	NSObject<TabExposeDelegate>* _delegate;
	UIImageView* _backgroundGradientView;
	UIScrollView* _scrollView;
	PagedTabExposeHitTestingView* _scrollViewHitTestingView;
	UIView* _scrollViewContentView;
	UILabel* _tabTitleView;
	UILabel* _tabURLView;
	TabScrollIndicatorContainerView* _pageIndicatorContainerView;
	UIPageControl* _pageIndicator;
	unsigned _documentIndex;
	NSArray* _toolbarItems;
	UIBarButtonItem* _newPageItem;
	BOOL _showing;
	BOOL _animating;
	BOOL _animatingAway;
	NSMutableArray* _tabDocuments;
	NSMutableArray* _pendingTabDocuments;
	NSArray* _allTabDocuments;
	TabDocument* _documentToActivate;
	TabDocument* _documentToClose;
}
@property(readonly, assign, nonatomic) TabDocument* centeredTabDocument;
@property(retain, nonatomic) TabDocument* documentToClose;
@property(retain, nonatomic) TabDocument* documentToActivate;
@property(readonly, assign, nonatomic, getter=isShowing) BOOL showing;
+(id)_textEtchColor;
+(id)_urlColor;
+(id)_urlFont;
+(id)_titleFont;
-(void)TabScrollIndicatorLeftPress:(id)press;
-(void)TabScrollIndicatorRightPress:(id)press;
-(void)_animateSlideLeft:(BOOL)left;
-(void)animateAddNewTabDocument:(id)document;
-(void)removeDocument:(id)document withNextTabDocument:(id)nextTabDocument animated:(BOOL)animated completion:(id)completion;
-(void)_slideTabButtonAtIndex:(int)index startingAtIndex:(int)index2 inDirection:(int)direction completion:(id)completion;
-(void)_layoutTabButton:(id)button withIndex:(int)index;
-(void)slideTabButtonsIntoPlaceAfterClosingTabDocument:(id)document completion:(id)completion;
-(void)animateScrollTabExposeView;
-(void)_finishedScrollLeftAnimation;
-(void)_animateScrollTabExposeViewLeft;
-(void)_finishedScrollRightAnimation;
-(void)_animateScrollTabExposeViewRight;
-(void)animateShowCloseButton:(BOOL)button;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollToDocument:(id)document;
-(void)scrollToDocument:(id)document animated:(BOOL)animated completion:(id)completion;
-(unsigned)documentIndex;
-(void)_updateDocumentIndex;
-(float)_deltaFromCenteredForDocument:(id)document;
-(CGPoint)scrollViewContentOffsetForDocument:(id)document;
-(BOOL)shouldUpdateThumbnails;
-(void)updateDirtyThumbnailsForTimer:(BOOL)timer;
-(void)hide;
-(void)_didHideWithActiveTabDocument:(id)activeTabDocument;
-(void)_didShow;
-(void)showAboveView:(id)view;
-(void)updateBackgroundGradient;
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(id)toolbarItems;
-(void)_doneButtonPressed;
-(void)_updateNewPageButtonState;
-(void)_newPageButtonPressed;
-(BOOL)shouldShowToolbarInFullscreen;
-(BOOL)shouldHideOnSuspend;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)pausesPages;
-(int)panelState;
-(int)panelType;
-(BOOL)handlesAnimations;
-(void)tile;
-(void)_tabButtonPressed:(id)pressed;
-(void)_activateCenteredDocument;
-(void)_updateTitleWithDocument:(id)document;
-(CGRect)_frameForButton:(id)button withIndex:(unsigned)index;
-(id)scrollView;
-(void)addTabButton:(id)button;
-(id)delegate;
-(void)setDelegate:(id)delegate;
-(void)setFrame:(CGRect)frame;
-(void)setAnimating:(BOOL)animating;
-(float)_maxThumbnailHeight;
-(BOOL)hasPendingTabDocuments;
-(void)removePendingTabDocument:(id)document;
-(void)addPendingTabDocument:(id)document;
-(void)setTabDocuments:(id)documents;
-(void)_updateVisibleTabDocuments;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

