/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BrowserPanel.h"
#import <Foundation/NSObject.h>

@class WebFrame, BrowserPrintPageRenderer;

__attribute__((visibility("hidden")))
@interface PrintBrowserPanel : NSObject <BrowserPanel> {
	BrowserPrintPageRenderer* _pageRenderer;
	WebFrame* _webFrame;
}
-(id)printControllerWithBrowserView:(id)browserView URLString:(id)string pageTitle:(id)title printFooter:(BOOL)footer;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)pausesPages;
-(int)panelState;
-(int)panelType;
-(void)dealloc;
-(id)initWithWebFrame:(id)webFrame;
@end

