/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "BackgroundDrawing.h"
#import <UIKit/UIView.h>

@class AddressView, UIImageView;

__attribute__((visibility("hidden")))
@interface ProgressView : UIView <BackgroundDrawing> {
	AddressView* _delegate;
	float _progress;
	BOOL _isShowingProgress;
	BOOL _drawActiveBackground;
	BOOL _usesPrivateBrowsingStyle;
	UIImageView* _backgroundImageView;
	UIImageView* _progressImageView;
}
-(void)setDrawActiveBackground:(BOOL)background;
-(void)drawBackgroundInContext:(CGContextRef)context;
-(void)setDelegate:(id)delegate;
-(void)setUsesPrivateBrowsingStyle:(BOOL)style;
-(void)layoutSubviews;
-(void)_updateImageViewGeometry:(id)geometry forProgress:(float)progress;
-(id)_backgroundImage;
-(id)_progressImage;
-(id)_inactiveBackgroundImage;
-(id)_activeBackgroundImage;
-(float)progress;
-(void)setProgress:(float)progress;
-(void)_updateShowsProgress;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

