/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>
#import "QLContentView.h"

@class QuickLookBannerView, QLDocumentInfoView;

__attribute__((visibility("hidden")))
@interface QLContentViewIPhone : UIView <QLContentView> {
	QLDocumentInfoView* _documentInfoView;
	QuickLookBannerView* _bannerView;
}
-(void)updateWithQuickLookDocument:(id)quickLookDocument;
-(void)showBanner;
-(void)hideBanner;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame quickLookBannerViewDelegate:(id)delegate;
@end

