/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "NSObject.h"


@protocol QLContentView <NSObject>
-(void)updateWithQuickLookDocument:(id)quickLookDocument;
-(void)showBanner;
-(void)hideBanner;
-(id)initWithFrame:(CGRect)frame quickLookBannerViewDelegate:(id)delegate;
@end

