/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class UILabel, UIImageView;

__attribute__((visibility("hidden")))
@interface QLDocumentInfoView : UIView {
	UILabel* _documentNameLabel;
	UILabel* _documentSizeLabel;
	UIImageView* _iconImageView;
}
@property(retain, nonatomic) UIImageView* iconImageView;
@property(retain, nonatomic) UILabel* documentSizeLabel;
@property(retain, nonatomic) UILabel* documentNameLabel;
-(void)updateWithQuickLookDocument:(id)quickLookDocument;
-(id)_iconImageForDocumentProxy:(id)documentProxy;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

