/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@protocol QLContentView;

__attribute__((visibility("hidden")))
@interface QuickLookDocumentView : UIView {
	UIView<QLContentView>* _contentView;
}
-(void)dealloc;
-(void)updateWithQuickLookDocument:(id)quickLookDocument;
-(void)showBanner;
-(void)hideBanner;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame quickLookBannerViewDelegate:(id)delegate;
@end

