/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <Foundation/NSObject.h>
#import "QuickLookBannerViewDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UIDocumentInteractionControllerDelegatePrivate.h"

@class TabDocument, UIDocumentInteractionController, QuickLookBannerView;

__attribute__((visibility("hidden")))
@interface QuickLookBannerController : NSObject <QuickLookBannerViewDelegate, UIDocumentInteractionControllerDelegate, UIDocumentInteractionControllerDelegatePrivate> {
	QuickLookBannerView* _quickLookBannerView;
	UIDocumentInteractionController* _documentInteractionController;
	TabDocument* _tabDocument;
	BOOL _isShowingQuickLookOpenInMenu;
}
@property(retain, nonatomic) UIDocumentInteractionController* documentInteractionController;
@property(readonly, assign, nonatomic) QuickLookBannerView* bannerView;
-(id)documentProxyForPreview:(id)preview name:(id)name UTI:(id)uti;
-(id)documentInteractionControllerURLOfDirectoryForUnzippedDocument:(id)unzippedDocument;
-(void)documentInteractionController:(id)controller willBeginSendingToApplication:(id)application;
-(void)documentInteractionControllerDidDismissOpenInMenu:(id)documentInteractionController;
-(void)documentInteractionControllerWillPresentOpenInMenu:(id)documentInteractionController;
-(void)openInOtherApplications:(id)otherApplications;
-(void)openInApplication:(id)application;
-(id)_urlForQuickLookDocument;
-(void)_savePDFDocumentToFileIfNeeded;
-(void)showBannerView;
-(void)hideBannerView;
-(void)_removeBannerViewTimer;
-(void)_addOrRestartBannerViewTimer;
-(void)dealloc;
-(id)initWithTabDocument:(id)tabDocument;
@end

