/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class UIToolbar, UIBarButtonItem, OpenInApplicationBarButtonItem;

__attribute__((visibility("hidden")))
@interface QuickLookBannerView : UIView {
	UIBarButtonItem* _fileNameItem;
	UIBarButtonItem* _flexibleSpaceItem;
	OpenInApplicationBarButtonItem* _openInApplicationItem;
	UIBarButtonItem* _openInOtherApplicationsItem;
	UIToolbar* _toolbar;
}
-(void)animateOut;
-(void)animateIn;
-(void)_animateTo:(float)to;
-(BOOL)updateWithQuickLookDocument:(id)quickLookDocument;
-(void)setFrame:(CGRect)frame;
-(void)_updateFileNameView;
-(void)dealloc;
-(BOOL)canScrollOffScreen;
-(float)bannerHeight;
-(id)initWithFrame:(CGRect)frame quickLookBannerViewDelegate:(id)delegate;
@end

