/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <Foundation/NSObject.h>
#import "QuickLookBannerViewDelegate.h"
#import "UIDocumentInteractionControllerDelegate.h"
#import "UIDocumentInteractionControllerDelegatePrivate.h"

@class QuickLookDocumentView, TabDocument, UIDocumentInteractionController;

__attribute__((visibility("hidden")))
@interface QuickLookDocumentController : NSObject <QuickLookBannerViewDelegate, UIDocumentInteractionControllerDelegate, UIDocumentInteractionControllerDelegatePrivate> {
	QuickLookDocumentView* _documentView;
	TabDocument* _tabDocument;
	UIDocumentInteractionController* _documentInteractionController;
	BOOL _isShowingQuickLookOpenInMenu;
}
@property(retain, nonatomic) QuickLookDocumentView* documentView;
@property(retain, nonatomic) UIDocumentInteractionController* documentInteractionController;
-(id)documentProxyForPreview:(id)preview name:(id)name UTI:(id)uti;
-(void)documentInteractionController:(id)controller willBeginSendingToApplication:(id)application;
-(void)documentInteractionControllerDidDismissOpenInMenu:(id)documentInteractionController;
-(void)documentInteractionControllerWillPresentOpenInMenu:(id)documentInteractionController;
-(void)openInOtherApplications:(id)otherApplications;
-(void)openInApplication:(id)application;
-(id)_urlForQuickLookDocument;
-(void)dealloc;
-(id)initWithTabDocument:(id)tabDocument;
@end

