/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class LSDocumentProxy, NSString;

__attribute__((visibility("hidden")))
@interface QuickLookDocument : NSObject {
	LSDocumentProxy* _documentProxy;
	BOOL _needsQuickLookDocumentView;
	NSString* _savedPath;
	NSString* _savedPathWithProperExtension;
	BOOL _shouldDeleteSavedPath;
	BOOL _shouldDeleteSavedPathWithProperExtension;
	NSString* _fileName;
	NSString* _mimeType;
	NSString* _uti;
}
@property(copy, nonatomic) NSString* uti;
@property(copy, nonatomic) NSString* mimeType;
@property(copy, nonatomic) NSString* fileName;
@property(copy, nonatomic) NSString* savedPathWithProperExtension;
@property(copy, nonatomic) NSString* savedPath;
@property(readonly, assign, nonatomic) BOOL needsQuickLookDocumentView;
@property(retain, nonatomic) LSDocumentProxy* documentProxy;
-(void)addQuickLookPrintSettingsToPrintInfo:(id)printInfo;
-(void)setSavedPathWithProperExtension:(id)properExtension shouldDelete:(BOOL)aDelete;
-(void)setSavedPath:(id)path shouldDelete:(BOOL)aDelete;
-(void)_deleteSavedPathWithProperExtensionIfNecessary;
-(void)_deleteSavedPathIfNecessary;
-(void)dealloc;
-(id)initWithFileName:(id)fileName mimeType:(id)type uti:(id)uti needsQuickLookDocumentView:(BOOL)view;
@end

