/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface ReadingListPreviewView : UIView {
	CGImageRef _iconImage;
	NSString* _title;
	NSString* _host;
	NSString* _previewText;
	NSString* _archiveStatusText;
	BOOL _drawsIcon;
	BOOL _highlighted;
	BOOL _read;
	BOOL _makeRoomForProgressGear;
}
@property(assign, nonatomic, getter=isRead) BOOL read;
@property(assign, nonatomic, getter=isHighlighted) BOOL highlighted;
@property(assign, nonatomic) BOOL drawsIcon;
@property(copy, nonatomic) NSString* archiveStatusText;
@property(copy, nonatomic) NSString* previewText;
@property(copy, nonatomic) NSString* host;
@property(copy, nonatomic) NSString* title;
-(void)drawRect:(CGRect)rect;
-(void)_drawIcon;
-(id)_previewColor;
-(id)_textColor;
-(void)_setArchiveStatusTextOrPreviewTextForBookmark:(id)bookmark;
-(void)setBookmark:(id)bookmark isArchiving:(BOOL)archiving;
-(void)setBookmark:(id)bookmark;
-(CGImageRef)_copyBestImageForBookmark:(id)bookmark;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

