/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ReaderActionDelegate.h"
#import "MobileSafari-Structs.h"
#import <Foundation/NSObject.h>

@class WebView, NSTimer;
@protocol ReaderControllerDelegate;

__attribute__((visibility("hidden")))
@interface ReaderContext : NSObject <ReaderActionDelegate> {
	int _retainCount;
	ReaderController* _readerController;
	ReaderJSController* _readerJSController;
	WebView* _webView;
	NSTimer* _clearUnusedReaderResourcesTimer;
	id<ReaderControllerDelegate> _delegate;
}
@property(assign, nonatomic) id<ReaderControllerDelegate> delegate;
@property(readonly, assign, nonatomic) ReaderController* readerController;
@property(readonly, assign, nonatomic) WebView* webView;
-(void)decreaseTextSize;
-(void)increaseTextSize;
-(void)createArticleFinder;
-(BOOL)shouldCreateArticleFinder;
-(void)webView:(id)view didClearWindowObject:(id)object forFrame:(id)frame;
-(void)webView:(id)view decidePolicyForNavigationAction:(id)navigationAction request:(id)request frame:(id)frame decisionListener:(id)listener;
-(BOOL)networkIsReachable;
-(int)readerOperationMode;
-(void)_clearUnusedReaderResources;
-(void)cancelClearUnusedReaderResourcesTimer;
-(void)clearUnusedReaderResourcesSoon;
-(void)loadNewArticle;
-(void)loadReaderDocument;
-(id)readerURL;
-(void)_clearReaderViewAndController;
-(ReaderJSController*)_readerJSController;
-(void)dealloc;
-(void)initReaderJSController:(id)controller;
-(id)mailingAndPrintingFrame;
-(BOOL)isReaderAvailable;
-(void)stopLoadingNextPage;
-(BOOL)isLoadingNextPage;
-(BOOL)hasMultiplePages;
-(void)clearAvailability;
-(void)clearReaderView;
-(void)createWebViewIfNeeded;
-(BOOL)_isDeallocating;
-(BOOL)_tryRetain;
-(unsigned)retainCount;
-(oneway void)release;
-(id)retain;
-(id)initWithWebView:(id)webView;
@end

