/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIWebView.h>

@class ReaderContext;

__attribute__((visibility("hidden")))
@interface ReaderWebView : UIWebView {
	ReaderContext* _readerContext;
}
-(id)initWithReaderContext:(id)readerContext;
-(void)view:(id)view didSetFrame:(CGRect)frame oldFrame:(CGRect)frame3;
-(void)scrollViewDidScroll:(id)scrollView;
@end

