/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WebBookmarksClientDelegateProtocol.h"
#import "MobileSafari-Structs.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import <UIKit/UIViewController.h>
#import "BookmarksPanelStateRestoring.h"

@class NSTimer, WebBookmarkCollection, UITableView, NSString, UISegmentedControl, EmptyCollectionExplanationView, WebBookmarksServerProxy, WebBookmarkList;

__attribute__((visibility("hidden")))
@interface ReadingListViewController : UIViewController <BookmarksPanelStateRestoring, UITableViewDelegate, UITableViewDataSource, WebBookmarksClientDelegateProtocol> {
	UISegmentedControl* _filterControl;
	UITableView* _tableView;
	WebBookmarkCollection* _collection;
	BOOL _showAllBookmarks;
	BOOL _networkIsReachable;
	WebBookmarkList* _readingList;
	WebBookmarksServerProxy* _webBookmarksServerProxy;
	NSString* _archivingBookmarkUUID;
	EmptyCollectionExplanationView* _explanationView;
	float _restoredScrollPosition;
	NSTimer* _deletionNotificationTimer;
}
@property(readonly, assign, nonatomic) NSString* collectionType;
@property(readonly, assign, nonatomic) BOOL showingAllBookmarks;
-(void)bookmarksServerProxy:(id)proxy didStopFetchingReadingListItem:(id)item;
-(void)bookmarksServerProxy:(id)proxy didStartFetchingReadingListItem:(id)item;
-(void)bookmarksServerProxyConnectionInvalidated:(id)invalidated;
-(void)bookmarksServerProxyDidFinishFetching:(id)bookmarksServerProxy;
-(void)restoreScrollPosition:(float)position;
-(float)currentScrollPosition;
-(BOOL)restoreStateWithDictionary:(id)dictionary;
-(id)currentStateDictionary;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)tableView:(id)view commitEditingStyle:(int)style forRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)_disconnectWebBookmarksServerProxy;
-(void)_connectWebBookmarksServerProxy;
-(void)_postChangeNotification;
-(void)_scheduleDelayedChangeNotification;
-(CGSize)contentSizeForViewInPopoverView;
-(void)_updatePopoverSize;
-(void)_done;
-(void)didMarkBookmarkUnreadAtIndex:(unsigned)index;
-(void)didAddNewReadingListBookmark;
-(void)_fetchIconsForVisibleReadingListItems;
-(void)_didDownloadIcons:(id)icons;
-(void)_addReadingListItem;
-(void)_didChangeFilter;
-(void)_reloadReadingListAndTable;
-(void)_reloadReadingList;
-(void)_networkReachabilityChanged:(id)changed;
-(id)_bookmarkAtIndexPath:(id)indexPath;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)_adjustTableViewInsetsForOrientation:(int)orientation;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)updateAddBookmarkButtonEnabledWithTabDocument:(id)tabDocument;
-(void)setAddBookmarkButtonEnabled:(BOOL)enabled;
-(void)loadView;
-(void)_clearExplanationView;
-(void)_setupExplanationView;
-(id)bookmarksNavigationController;
-(void)dealloc;
-(id)init;
@end

