/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIButton.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface ReaderButtonView : UIButton {
	CGSize _defaultSize;
	UIImage* _showReaderNormal;
	UIImage* _hideReaderNormal;
	UIImage* _hideReaderPressed;
	UIImage* _showReaderPressed;
}
-(void)dealloc;
-(CGSize)defaultSize;
-(void)setHideShowImage:(BOOL)image;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame;
-(float)_defaultWidthForTitle:(id)title;
-(id)_font;
@end

