/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewCell.h>

@class UIActivityIndicatorView, UIImageView, ReadingListPreviewView;

__attribute__((visibility("hidden")))
@interface ReadingListTableViewCell : UITableViewCell {
	ReadingListPreviewView* _previewView;
	UIImageView* _previousContentView;
	unsigned _bookmarkID;
	UIActivityIndicatorView* _archiveProgressGear;
}
@property(readonly, assign, nonatomic) unsigned bookmarkID;
-(void)setSelected:(BOOL)selected animated:(BOOL)animated;
-(void)didTransitionToState:(unsigned)state;
-(void)willTransitionToState:(unsigned)state;
-(void)_clearPreviousContentView;
-(void)setBookmark:(id)bookmark isArchiving:(BOOL)archiving;
-(void)setBookmark:(id)bookmark;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(int)style reuseIdentifier:(id)identifier;
@end

