/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class UIButton;

__attribute__((visibility("hidden")))
@interface ReaderActionView : UIView {
	UIButton* _increaseTextSizeButton;
	UIButton* _decreaseTextSizeButton;
}
+(void)updateButtonStyle:(id)style;
-(void)dealloc;
-(void)layoutSubviews;
-(id)initWithFrame:(CGRect)frame delegate:(id)delegate;
@end

