/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UITableViewController.h>

@class NSMutableArray;
@protocol RecentlyClosedTabViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface RecentlyClosedTabViewController : UITableViewController {
	NSMutableArray* _recentlyClosedTabs;
	id<RecentlyClosedTabViewControllerDelegate> _delegate;
}
@property(assign, nonatomic) id<RecentlyClosedTabViewControllerDelegate> delegate;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(CGSize)contentSizeForViewInPopover;
-(void)viewWillAppear:(BOOL)view;
-(void)removeAllRecentlyClosedTabDocuments;
-(void)removeRecentlyClosedTabDocument:(id)document;
-(void)addRecentlyClosedTabDocument:(id)document;
-(void)dealloc;
-(id)initWithStyle:(int)style;
@end

