/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIButton.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface ReloadImageView : UIButton {
	UIImage* _reloadImage;
	UIImage* _stopImage;
	BOOL _stopShown;
	BOOL _stopDrawn;
	id _delegate;
}
-(void)setUsesPrivateBrowsingStyle:(BOOL)style;
-(void)setCoalescedDisplayIfNeeded;
-(void)setDelegate:(id)delegate;
-(CGSize)defaultSize;
-(void)setStopShown:(BOOL)shown forceUpdate:(BOOL)update;
-(void)updateImage;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

