/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UIActionSheetDelegate.h"
#import <Foundation/NSObject.h>
#import "RotatableBrowserPanel.h"

@class UIActionSheet;

__attribute__((visibility("hidden")))
@interface RotatableActionSheetPanel : NSObject <RotatableBrowserPanel, UIActionSheetDelegate> {
	UIActionSheet* _sheet;
}
-(void)didRotateFromInterfaceOrientation:(int)interfaceOrientation;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)didPresentActionSheet:(id)sheet;
-(void)actionSheet:(id)sheet didDismissWithButtonIndex:(int)buttonIndex;
-(void)actionSheet:(id)sheet willDismissWithButtonIndex:(int)buttonIndex;
-(void)setVisible:(BOOL)visible animate:(BOOL)animate;
-(BOOL)handlesAnimations;
-(int)pausesPages;
-(int)panelState;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)panelType;
-(void)dealloc;
@end

