/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class SearchEngineController, NSDictionary, NSMutableString, NSString;

__attribute__((visibility("hidden")))
@interface SearchEngineInfo : NSObject {
	NSString* _shortName;
	NSString* _scriptName;
	int _searchID;
	NSString* _searchURLTemplate;
	NSString* _suggestionsURLTemplate;
	NSDictionary* _topLevelDomains;
	NSString* _carrierInfo;
	NSMutableString* _searchURL;
	SearchEngineController* _controller;
}
@property(retain, nonatomic) NSDictionary* topLevelDomains;
@property(retain, nonatomic) NSString* suggestionsURLTemplate;
@property(retain, nonatomic) NSString* shortName;
@property(retain, nonatomic) NSString* searchURLTemplate;
@property(retain, nonatomic) NSMutableString* searchURL;
@property(retain, nonatomic) NSString* scriptName;
@property(retain, nonatomic) SearchEngineController* controller;
@property(retain, nonatomic) NSString* carrierInfo;
+(id)engineFromDictionary:(id)dictionary withController:(id)controller;
-(void)dealloc;
-(id)description;
-(id)searchURLForQuery:(id)query;
-(void)setSearchURL;
-(id)getTopLevelDomainFor:(id)aFor;
-(int)searchID;
-(id)initWithName:(id)name scriptName:(id)name2 searchID:(int)anId searchTemplate:(id)aTemplate suggestionsTemplate:(id)aTemplate5 topLevelDomains:(id)domains controller:(id)controller;
@end

