/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class WebScriptObject;

__attribute__((visibility("hidden")))
@interface SetSearchEngineScriptObject : NSObject {
	WebScriptObject* _windowObject;
}
-(id)invokeDefaultMethodWithArguments:(id)arguments;
-(void)dealloc;
-(id)initWithWindowObject:(id)windowObject;
@end

