/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>


__attribute__((visibility("hidden")))
@interface Settings : NSObject {
}
+(id)historyPath;
+(id)configurableSearchEngineFallbackPath;
+(id)configurableSearchEnginePath;
+(id)cachesDirectoryPath;
+(id)recentSearchPath;
+(id)thumbnailCacheDirectoryPath;
+(id)savedStatePath;
+(id)settingsDirectoryPath;
@end

