/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



__attribute__((visibility("hidden")))
@interface SharedDataMigration {
}
+(void)migrateWebPreferences;
+(BOOL)migrateThumbnails;
+(BOOL)migrateRecentSearches;
+(void)migratePersistentStorageDefaults;
-(BOOL)_migrateCacheFileFromSubpath:(id)subpath toSubpath:(id)subpath2 ensureIsDirectory:(BOOL)directory;
-(id)_userCachesDirectoryPath;
@end

