/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BrowserPanel.h"
#import <Foundation/NSObject.h>

@class SheetController;

__attribute__((visibility("hidden")))
@interface SheetControllerPanel : NSObject <BrowserPanel> {
	SheetController* _sheetController;
}
@property(readonly, assign, nonatomic) SheetController* sheetController;
-(BOOL)ignoresPrivateBrowsingStyle;
-(int)pausesPages;
-(int)panelState;
-(int)panelType;
-(void)dealloc;
-(id)initWithSheetController:(id)sheetController;
@end

