/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSURLConnection, NSMutableData, NSMutableArray;

__attribute__((visibility("hidden")))
@interface SiteIconDownloader : NSObject {
	unsigned _bookmarkID;
	NSMutableArray* _URLs;
	NSURLConnection* _connection;
	NSMutableData* _data;
}
+(void)setShouldContinueDownloadingReadingListIcons:(BOOL)continueDownloadingReadingListIcons;
+(BOOL)downloadIsPendingForBookmarkID:(unsigned)bookmarkID;
+(void)cancelAllDownloads;
+(void)downloadIconsForBrowserView:(id)browserView forReadingListBookmarkID:(unsigned)readingListBookmarkID;
+(void)downloadFallbackIconsForURL:(id)url forReadingListBookmarkID:(unsigned)readingListBookmarkID;
-(unsigned)bookmarkID;
-(void)_removeFromIconDownloadersAndScheduleNextDownloadIfNeeded;
-(void)cancel;
-(void)connectionDidFinishLoading:(id)connection;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(void)connection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;
-(void)_cancelConnectionAndFetchNextIcon;
-(void)_fetchNextIcon;
-(void)dealloc;
-(id)_initWithIconURLs:(id)iconURLs readingListBookmarkID:(unsigned)anId;
@end

