/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol SKProductPageViewControllerDelegate <NSObject>
@optional
-(void)productPage:(id)page presentProductPage:(id)page2 animated:(BOOL)animated;
-(void)productPage:(id)page willMakePurchases:(id)purchases;
-(void)productPage:(id)page didReceiveTitle:(id)title;
-(void)productPage:(id)page purchaseBatchFailedWithError:(id)error;
-(void)productPage:(id)page didFinishPurchase:(id)purchase withError:(id)error;
-(void)productPage:(id)page didFinishWithResult:(int)result;
-(void)productPageDidFinishLoad:(id)productPage;
-(void)productPage:(id)page didFailLoadWithError:(id)error;
@end

