/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIBarButtonItem.h>


__attribute__((visibility("hidden")))
@interface SpacedBarButtonItem : UIBarButtonItem {
	UIBarButtonItem* _precedingFixedSpace;
}
@property(readonly, assign, nonatomic) UIBarButtonItem* precedingFixedSpace;
-(void)dealloc;
-(id)init;
@end

