/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "SKProductPageViewControllerDelegate.h"
#import <UIKit/UIView.h>

@class SKProductPageViewController, NSNumber, NSString, UIImageView;
@protocol StoreBannerDelegate;

__attribute__((visibility("hidden")))
@interface StoreBanner : UIView <SKProductPageViewControllerDelegate> {
	SKProductPageViewController* _productViewController;
	UIImageView* _bottomShadowView;
	NSNumber* _productID;
	NSString* _affiliateData;
	id<StoreBannerDelegate> _delegate;
	BOOL _isPinnedToTop;
}
@property(assign, nonatomic) BOOL isPinnedToTop;
+(void)storeBannerForMetaTagInDocument:(id)document delegate:(id)delegate completion:(id)completion;
+(id)_valueFromKeyValueString:(id)keyValueString;
-(void)productPage:(id)page didFinishPurchase:(id)purchase withError:(id)error;
-(void)productPage:(id)page willMakePurchases:(id)purchases;
-(void)productPage:(id)page didFailLoadWithError:(id)error;
-(void)productPage:(id)page didFinishWithResult:(int)result;
-(void)dealloc;
-(void)_setBlockedByUser;
-(id)snapshotImageView;
-(void)setFrame:(CGRect)frame;
-(id)initWithFrame:(CGRect)frame forProductID:(id)productID affiliateData:(id)data applicationLaunchArgument:(id)argument delegate:(id)delegate;
@end

