/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class ThumbnailImageView, NSString, UIButton, UIImageView;

__attribute__((visibility("hidden")))
@interface TabButton : UIView {
	ThumbnailImageView* _thumbnailImageView;
	UIImageView* _thumbnailShadowView;
	UIButton* _closeButton;
	CGRect _closeButtonHitRect;
	BOOL _hasCloseButton;
	NSString* _urlString;
	CGPoint _closeButtonOffset;
	CGSize _thumbnailSize;
	id _target;
	SEL _action;
}
+(id)_closeButtonPressedImage;
+(id)_closeButtonImage;
-(id)snapshot;
-(void)setSnapshot:(id)snapshot animated:(BOOL)animated;
-(BOOL)hasCloseButton;
-(void)setHasCloseButton:(BOOL)button;
-(void)insertThumbnailImageView;
-(id)thumbnailImageView;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)_thumbnailImagePressed;
-(void)setTarget:(id)target action:(SEL)action;
-(id)closeButton;
-(void)setDimAlpha:(float)alpha;
-(CGSize)thumbnailSize;
-(void)setThumbnailSize:(CGSize)size;
-(void)setFrame:(CGRect)frame;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
-(void)_tile;
@end

