/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString, TabBarItemView, TabBar;

__attribute__((visibility("hidden")))
@interface TabBarItem : NSObject {
	TabBarItemView* _view;
	TabBar* _tabBar;
	NSString* _title;
	BOOL _active;
	int _securityLevel;
}
@property(assign, nonatomic) int securityLevel;
@property(assign, nonatomic, getter=isActive) BOOL active;
@property(copy, nonatomic) NSString* title;
-(void)clearView;
-(void)setTabBar:(id)bar;
-(void)moreTabsButtonPressed;
-(void)closeButtonPressed;
-(BOOL)hasView;
-(id)view;
-(void)dealloc;
@end

