/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "MobileSafari-Structs.h"

@class NSString, TabBar;

__attribute__((visibility("hidden")))
@interface TabBarPieceView : UIView {
	TabBar* _tabBar;
	CGSize _desiredSize;
	BOOL _backgroundPiece;
	BOOL _animatingBackgroundOffset;
	NSString* _type;
}
@property(copy, nonatomic) NSString* type;
-(void)animateBackgroundFromOffset:(float)offset toOffset:(float)offset2;
-(CGSize)sizeThatFits:(CGSize)fits;
-(void)dealloc;
-(id)initWithType:(id)type tabBar:(id)bar;
-(id)initWithType:(id)type tabBar:(id)bar backgroundPiece:(BOOL)piece;
-(void)_updateContents;
@end

