/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIView.h>

@class NSString, UIButton, FloatingHighlightButton, TabBar, UIImageView, TabBarPieceView, UILabel;

__attribute__((visibility("hidden")))
@interface TabBarItemView : UIView {
	TabBarPieceView* _leftEdge;
	TabBarPieceView* _middle;
	TabBarPieceView* _rightEdge;
	UILabel* _titleLabel;
	NSString* _titleText;
	UIImageView* _lockView;
	TabBar* _tabBar;
	FloatingHighlightButton* _closeButton;
	FloatingHighlightButton* _moreTabsButton;
	BOOL _active;
	int _securityLevel;
	BOOL _showsLeftEdge;
	BOOL _showsRightEdge;
	BOOL _centersTitleInWindow;
	BOOL _showsMoreTabsButton;
}
@property(readonly, assign, nonatomic) CGRect extendedFrame;
@property(assign, nonatomic) BOOL showsMoreTabsButton;
@property(readonly, assign, nonatomic) UIButton* moreTabsButton;
@property(assign, nonatomic) BOOL centersTitleInWindow;
@property(assign, nonatomic) BOOL showsRightEdge;
@property(assign, nonatomic) BOOL showsLeftEdge;
@property(assign, nonatomic) int securityLevel;
@property(assign, nonatomic, getter=isActive) BOOL active;
@property(readonly, assign, nonatomic) UIButton* closeButton;
+(float)extraWidthForMoreTabsButton;
-(void)dealloc;
-(void)setTitleText:(id)text;
-(void)setFrame:(CGRect)frame;
-(void)setBounds:(CGRect)bounds;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(id)initWithTabBar:(id)tabBar;
-(void)_layoutMoreTabsButton;
-(void)_layoutCloseButton;
-(void)_layoutLockView;
-(void)_layoutEdges;
-(void)updateTitleTruncation;
-(void)_layoutTitleLabel;
-(CGRect)_titleBoundingBox;
-(CGRect)_contentRect;
-(id)_truncatedTitleWithFont:(id)font desiredWidth:(float)width truncatedSize:(CGSize*)size;
@end

