/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol TabBarDelegate
-(void)tabBar:(id)bar closeItem:(id)item;
-(void)tabBar:(id)bar activateItem:(id)item;
-(void)tabBar:(id)bar moveItem:(id)item overItem:(id)item3;
-(void)tabBarAddTab:(id)tab;
-(void)tabBarShowMoreTabs:(id)tabs;
-(void)tabBarAddTabLongPress:(id)press;
-(BOOL)tabBar:(id)bar canCloseItem:(id)item;
-(BOOL)tabBar:(id)bar canMoveItem:(id)item;
-(BOOL)tabBarCanAddTab:(id)tab;
@end

