/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol TabDocumentDelegate
-(void)setStoreBannerPinnedToTop:(BOOL)top forTabDocument:(id)tabDocument;
-(void)removeStoreBannerFromTabDocument:(id)tabDocument animated:(BOOL)animated;
-(void)setShowingStoreBanner:(id)banner isShowing:(BOOL)showing;
-(void)composeEmailWithMailToURL:(id)url forTabDocument:(id)tabDocument;
-(void)hideAlertForTabDocument:(id)tabDocument;
-(void)showAlertForTabDocument:(id)tabDocument;
-(void)tabDocument:(id)document didCancelAuthenticationChallenge:(id)challenge;
-(void)tabDocument:(id)document didReceiveAuthenticationChallenge:(id)challenge fromDataSource:(id)dataSource;
-(void)tabDocumentStoppedLoadingResource:(id)resource;
-(void)tabDocumentStartedLoadingResource:(id)resource;
-(void)tabDocument:(id)document progressChanged:(float)changed;
-(void)tabDocumentDidUpdateBackForward:(id)tabDocument;
-(void)tabDocumentDidUpdateURL:(id)tabDocument;
-(void)tabDocumentDidUpdateTitle:(id)tabDocument;
-(void)tabDocumentProgressDidStall:(id)tabDocumentProgress;
-(void)tabDocument:(id)document didFinishLoadingWithError:(BOOL)error;
-(void)tabDocumentDidStartLoading:(id)tabDocument;
@end

