/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol TabExposeDelegate <NSObject>
-(void)tabExposeView:(id)view didHideWithActiveTabDocument:(id)activeTabDocument;
-(void)tabExposeViewDidShow:(id)tabExposeView;
-(void)tabExposeViewWillHide:(id)tabExposeView;
-(void)tabExposeView:(id)view willShowAboveView:(id)view2;
-(BOOL)tabExposeViewCanAddTab:(id)tab;
-(void)tabExposeViewAddTab:(id)tab;
-(void)tabExposeView:(id)view activateTabDocument:(id)document;
-(void)tabExposeView:(id)view closeTabDocument:(id)document;
-(id)activeTabDocument;
@end

