/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class LSApplicationProxy, NSURL;

__attribute__((visibility("hidden")))
@interface TabNavigationResult : NSObject {
	int _type;
	NSURL* _URL;
	LSApplicationProxy* _externalApplication;
}
@property(readonly, assign, nonatomic) LSApplicationProxy* externalApplication;
@property(readonly, assign, nonatomic) NSURL* URL;
@property(readonly, assign, nonatomic) int type;
+(id)resultWithRedirectToExternalURL:(id)externalURL;
+(id)resultOfType:(int)type withURL:(id)url;
-(id)_initWithType:(int)type URL:(id)url externalApplication:(id)application;
-(void)dealloc;
@end

