/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UITableViewController.h>
#import "MobileSafari-Structs.h"

@class NSArray, TabDocument;
@protocol TabOverflowListControllerDelegate;

__attribute__((visibility("hidden")))
@interface TabOverflowListController : UITableViewController {
	NSArray* _tabDocuments;
	TabDocument* _selectedDocument;
	id<TabOverflowListControllerDelegate> _delegate;
}
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(CGSize)contentSizeForViewInPopover;
-(void)dealloc;
-(id)initWithTabDocuments:(id)tabDocuments selectedDocument:(id)document delegate:(id)delegate;
@end

