/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <UIKit/UIView.h>
#import "MobileSafari-Structs.h"


__attribute__((visibility("hidden")))
@interface TabScrollIndicatorContainerView : UIView {
	id _delegate;
}
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
-(void)setDelegate:(id)delegate;
-(void)dealloc;
@end

