/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <Foundation/NSObject.h>

@class UIColor, TabDocument, UIView;

__attribute__((visibility("hidden")))
@interface TabSnapshotContext : NSObject {
	BOOL _shouldRestoreBackgroundColor;
	UIView* _frontView;
	UIColor* _oldBackgroundColor;
	TabDocument* _activeTabDocumentBeforeTakingSnapshot;
	TabDocument* _tabDocumentToSnapshot;
	BOOL _activeTabDocumentWasChangedDuringSnapshot;
	CGRect _snapshotRect;
	float _contentsScale;
	BOOL _shouldAnimateUpdate;
}
@property(retain) TabDocument* tabDocumentToSnapshot;
@property(retain) UIView* frontView;
@property(assign) BOOL shouldAnimateUpdate;
@property(assign) float contentsScale;
@property(assign) CGRect snapshotRect;
@property(assign, nonatomic) BOOL activeTabDocumentWasChangedDuringSnapshot;
@property(retain, nonatomic) TabDocument* activeTabDocumentBeforeTakingSnapshot;
@property(retain, nonatomic) UIColor* oldBackgroundColor;
@property(assign, nonatomic) BOOL shouldRestoreBackgroundColor;
-(void)dealloc;
@end

