/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class PageLoadTestRunner, ApplicationTesting, NSTimer, NSString;

__attribute__((visibility("hidden")))
@interface TestProcessor : NSObject {
	NSTimer* _actionTimer;
	int _actionCount;
	NSString* _testName;
	ApplicationTesting* _applicationTesting;
	PageLoadTestRunner* _testRunner;
	BOOL _running;
	BOOL _shouldShowRenderTime;
	BOOL _shouldShowRenderFps;
}
-(void)setShouldShowRenderFps:(BOOL)showRenderFps;
-(void)setShouldShowRenderTime:(BOOL)showRenderTime;
-(BOOL)performActionForTimer;
-(void)_handleActionTimer;
-(void)pageLoadTestRunnerFinishedPageLoad:(id)load;
-(void)pageLoadTestRunnerFinishedTest:(id)test;
-(void)pageLoadTestRunnerStartedTest:(id)test;
-(void)dealloc;
-(id)initWithTestName:(id)testName applicationTesting:(id)testing;
-(id)init;
@end

