/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIButton.h>


__attribute__((visibility("hidden")))
@interface TouchEatingButton : UIButton {
}
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

