/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import "UIDocumentInteractionControllerDelegate.h"


@protocol UIDocumentInteractionControllerDelegatePrivate <UIDocumentInteractionControllerDelegate>
@optional
-(void)documentInteractionControllerWillEndPreview:(id)documentInteractionController;
-(id)printInfoForDocumentInteractionController:(id)documentInteractionController;
-(id)activityItemForDocumentInteractionController:(id)documentInteractionController;
-(id)additionalActivitiesForDocumentInteractionController:(id)documentInteractionController;
-(BOOL)shouldBlockRemoteImagesInPreviewForDocumentInteractionController:(id)documentInteractionController;
-(id)excludedActivityTypesForDocumentInteractionController:(id)documentInteractionController;
-(id)documentProxyForPreview:(id)preview name:(id)name UTI:(id)uti;
@end

