/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <Foundation/NSObject.h>

@class NSString;

__attribute__((visibility("hidden")))
@interface URLCompletionItem : NSObject {
	NSString* title;
	NSString* address;
	float weight;
}
@property(assign, nonatomic) float weight;
@property(retain, nonatomic) NSString* address;
@property(retain, nonatomic) NSString* title;
-(id)description;
-(void)dealloc;
-(id)initWithAddress:(id)address title:(id)title weight:(float)weight;
@end

