/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WebBookmarksClientDelegateProtocol <NSObject>
@optional
-(void)bookmarksServerProxyConnectionInvalidated:(id)invalidated;
-(void)bookmarksServerProxyDidFinishFetching:(id)bookmarksServerProxy;
-(void)bookmarksServerProxy:(id)proxy didUpdateReadingListFetchingProgress:(id)progress;
-(void)bookmarksServerProxy:(id)proxy didStopFetchingReadingListItem:(id)item;
-(void)bookmarksServerProxy:(id)proxy didStartFetchingReadingListItem:(id)item;
@end

