/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <WebBookmarks/WebBookmarkCollection.h>


@interface WebBookmarkCollection (SafariAdditions)
+(void)setInitialReadingListIconFetchingEnabled:(BOOL)enabled;
+(void)loadAccountBookmarkFromCarrierBundleDictionary:(id)carrierBundleDictionary ignoringDeletedBookmarks:(id)bookmarks intoArray:(id)array;
+(void)loadBookmarksFromCarrierBundleDictionary:(id)carrierBundleDictionary ignoringDeletedBookmarks:(id)bookmarks intoArray:(id)array;
+(id)staticCarrierBookmarksIgnoringDeletedBookmarks:(id)bookmarks;
+(id)staticBookmarks;
+(void)reloadStaticBookmarks;
+(BOOL)deleteStaticBookmark:(id)bookmark;
+(id)mainBookmarkCollection;
-(void)migrateYouTubeBookmarks;
-(id)_uniqueYouTubeBookmarkFolderName;
-(void)_markDuplicateReadingListBookmarkUnread:(id)unread updatingController:(id)controller;
-(void)fetchInitialMissingReadingListIconsForList:(id)list;
-(void)fetchInitialMissingReadingListIcons;
-(void)stopDownloadingReadingListIcons;
-(void)startDownloadingReadingListIcons;
-(int)populateIconForReadingListBookmark:(id)readingListBookmark allowDownloads:(BOOL)downloads;
-(void)receivedBookmarksDidReloadNotification:(id)receivedBookmarks;
-(BOOL)updateReadingListBookmarkWithID:(unsigned)anId setTitle:(id)title address:(id)address previewText:(id)text;
-(BOOL)markReadingListBookmarkWithIDAsRead:(unsigned)idasRead;
-(BOOL)saveReadingListBookmarkWithTitle:(id)title address:(id)address previewText:(id)text tabDocument:(id)document didFetchPage:(BOOL)page updateController:(id)controller;
@end

