/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol WebClipDelegate
@optional
-(void)webClip:(id)clip startupLandscapeImageRequestDidFinishWithImage:(id)startupLandscapeImageRequest;
-(void)webClip:(id)clip startupImageRequestDidFinishWithImage:(id)startupImageRequest;
-(void)webClip:(id)clip iconRequestDidFinishWithImage:(id)iconRequest precomposed:(BOOL)precomposed;
@end

