/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UITableViewCellLayoutManager.h>


__attribute__((visibility("hidden")))
@interface WebClipTableViewCellLayoutManager : UITableViewCellLayoutManager {
}
-(id)editableTextFieldForCell:(id)cell;
-(id)detailTextLabelForCell:(id)cell;
-(id)textLabelForCell:(id)cell;
-(void)layoutSubviewsOfCell:(id)cell;
-(CGRect)contentEndingRectForCell:(id)cell forNewEditingState:(BOOL)newEditingState;
-(CGRect)backgroundEndingRectForCell:(id)cell forNewEditingState:(BOOL)newEditingState;
@end

