/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MobileSafari-Structs.h"
#import <UIKit/UIViewController.h>
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSObject, UITableViewCell, UITableView, UIView, UIWebClip, UILabel;
@protocol WebClipViewControllerDelegate;

__attribute__((visibility("hidden")))
@interface WebClipViewController : UIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate> {
	UITableView* _tableView;
	UITableViewCell* _tableViewCell;
	UILabel* _infoLabel;
	UIView* _infoLabelContainer;
	BOOL _suspendAfterDismiss;
	UIWebClip* _webClip;
	NSObject<WebClipViewControllerDelegate>* _delegate;
	BOOL _delegateNotifiedOfResult;
}
@property(assign, nonatomic) NSObject<WebClipViewControllerDelegate>* delegate;
@property(retain) UIWebClip* webClip;
-(void)dealloc;
-(CGSize)contentSizeForViewInPopoverView;
-(BOOL)shouldShowButtonBar;
-(void)_textFieldChanged;
-(BOOL)textFieldShouldReturn:(id)textField;
-(BOOL)_canAddWebClip;
-(void)_add;
-(void)_cancel;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)updateUIAnimated:(BOOL)animated;
-(void)layoutSubviews;
-(float)tableViewTopMargin;
-(void)loadView;
-(id)init;
@end

