/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <WebKit/WebHistoryItem.h>


@interface WebHistoryItem (MobileSafariExtras)
-(void)setReadingListBookmarkID:(unsigned)anId;
-(unsigned)readingListBookmarkID;
@end

