/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WebUIBrowserLoadingControllerDelegate <NSObject>
@optional
-(void)webView:(id)view didFirstVisuallyNonEmptyLayoutInFrame:(id)frame;
-(void)webView:(id)view didClearWindowObject:(id)object forFrame:(id)frame;
-(void)webView:(id)view didChangeLocationWithinPageForFrame:(id)frame;
-(void)webView:(id)view didFailLoadWithError:(id)error forFrame:(id)frame;
-(void)webView:(id)view didFinishLoadForFrame:(id)frame;
-(void)webView:(id)view didCommitLoadForFrame:(id)frame;
-(void)webView:(id)view didFailProvisionalLoadWithError:(id)error forFrame:(id)frame;
-(void)webView:(id)view didReceiveServerRedirectForProvisionalLoadForFrame:(id)frame;
-(void)webView:(id)view didStartProvisionalLoadForFrame:(id)frame;
-(id)browserLoadingController:(id)controller userVisibleStringForURL:(id)url;
-(void)browserLoadingController:(id)controller didFinishLoadingWithError:(id)error dataSource:(id)source;
-(void)browserLoadingControllerDidStartLoading:(id)browserLoadingController;
-(void)browserLoadingControllerWillStartUserDrivenLoad:(id)browserLoadingController;
-(BOOL)browserLoadingControllerShouldShowProvisionalURLs:(id)browserLoadingController;
-(void)browserLoadingController:(id)controller willLoadRequest:(id)request userDriven:(BOOL)driven;
-(void)browserLoadingControllerDidUpdateEstimatedProgress:(id)browserLoadingController;
-(void)browserLoadingControllerDidUpdateSecurity:(id)browserLoadingController;
-(void)browserLoadingControllerDidUpdateBackForward:(id)browserLoadingController;
-(void)browserLoadingControllerDidUpdateTitle:(id)browserLoadingController;
-(void)browserLoadingControllerDidUpdateURLString:(id)browserLoadingController;
-(void)browserLoadingControllerDidUpdateURL:(id)browserLoadingController;
@end

