/**
 * This header is generated by class-dump-z 0.2-0.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <WebKit/WebView.h>


@interface WebView (SafariExtrasForFindOnPage)
-(id)_selectedOrMainFrame;
@end

@interface WebView (ReaderInternal)
-(id)currentURL;
@end

@interface WebView (MobileSafariExtras)
-(void)setWebHistoryItemReadingListBookmarkID:(unsigned)anId;
-(unsigned)webHistoryItemReadingListBookmarkID;
-(void)setSecurityInfo:(id)info;
-(id)securityInfo;
@end

